# Generated by Django 5.1.6 on 2025-02-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_userprofile_address_remove_userprofile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
