# Generated by Django 5.1.6 on 2025-02-27 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_delete_newslettersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=150, verbose_name='Physical Address'),
        ),
        migrations.AddField(
            model_name='profile',
            name='agency_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Agency Name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Primary Email'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='Contact Phone'),
        ),
    ]
